package it.polimi.ingsw.message;

public enum MessageType {
	LOGIN_REQUEST, LOGIN_REPLY,
	RESOURCES_LIST_MESSAGE, INPUT_SELECTION_MESSAGE,
	PLAYER_NUMBER_REQUEST, PLAYER_NUMBER_REPLY,
	INTERACTION_WITH_MARKET_MESSAGE,
	BUY_CARD_MESSAGE

}
