package it.polimi.ingsw.message;

public enum MessageType {
	LOGIN_REQUEST, LOGIN_REPLY,
	RESOURCES_LIST_MESSAGE, INPUT_SELECTION_MESSAGE,
	PLAYER_NUMBER_REQUEST, PLAYER_NUMBER_REPLY,
	INTERACTION_WITH_MARKET_MESSAGE,
	BUY_CARD_MESSAGE,
	DEPOT_INTERACTION_MESSAGE,
	FAITH_TRACK_MESSAGE,
	MARKET_MESSAGE,
	DEPOT_MESSAGE,
	PLAYER_CARDS_AND_PRODUCTION,

	GENERIC_MESSAGE,
	CARDS_DECK,
	ERROR_MESSAGE,
	DISCONNECTION_MESSAGE,
	WIN_MESSAGE

}
